name: 'spicy-proton generator'
description: |
  Deterministically generates a string in the form of "spicy-proton"
  that can be used to name deployments from a branch.
author: 'ScriptHero team'
inputs:
  name:
    description: 'Name of the branch that will be deployed'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
